function awardDefaultElements() { return [
  {kind:'AWARD_NAME',label:'Award name',x:.25,y:.10,width:.50,height:.08},
  {kind:'CALLSIGN',label:'Callsign',x:.35,y:.34,width:.30,height:.08},
  {kind:'PERSON_NAME',label:'Participant name',x:.25,y:.45,width:.50,height:.08},
  {kind:'DATE_OBTAINED',label:'Date obtained',x:.35,y:.57,width:.30,height:.06},
  {kind:'MANAGER_NAME',label:'Award manager',x:.20,y:.79,width:.35,height:.06},
  {kind:'MANAGER_SIGNATURE',label:'Manager signature',x:.60,y:.73,width:.25,height:.14}
]; }
function awardElementLabel(kind) { return {AWARD_NAME:'Award name',CALLSIGN:'Callsign',PERSON_NAME:'Participant name',DATE_OBTAINED:'Date obtained',MANAGER_NAME:'Award manager',MANAGER_SIGNATURE:'Manager signature'}[kind] || kind; }
function awardCanvas() { return `<div class="award-canvas" id="award-canvas" aria-label="Certificate layout preview"><div class="award-canvas-background">A4 / Letter certificate preview</div>${state.awardTemplateElements.map((element,index)=>`<div class="award-canvas-element ${element.kind==='MANAGER_SIGNATURE'?'signature-element':''}" data-award-element="${index}" style="left:${element.x*100}%;top:${element.y*100}%;width:${element.width*100}%;height:${element.height*100}%"><span>${esc(element.label || awardElementLabel(element.kind))}</span></div>`).join('')}</div>`; }
function awardElementRows() { return state.awardTemplateElements.map((element,index)=>`<div class="award-element-row"><strong>${esc(element.label || awardElementLabel(element.kind))}</strong><label>X<input type="number" step="0.01" min="0" max="1" data-award-field="${index}:x" value="${Number(element.x).toFixed(2)}"></label><label>Y<input type="number" step="0.01" min="0" max="1" data-award-field="${index}:y" value="${Number(element.y).toFixed(2)}"></label><label>Width<input type="number" step="0.01" min="0.01" max="1" data-award-field="${index}:width" value="${Number(element.width).toFixed(2)}"></label><label>Height<input type="number" step="0.01" min="0.01" max="1" data-award-field="${index}:height" value="${Number(element.height).toFixed(2)}"></label></div>`).join(''); }
function awardEditor(item = {}) {
  state.awardTemplateElements = cloneJson(item.template?.elements || awardDefaultElements());
  const background = item.backgroundAsset || {kind:'BACKGROUND',name:'Certificate background',objectKey:'',mediaType:'image/png',widthPx:2481,heightPx:3508};
  const print = item.printSpec || {page:'A4',orientation:'PORTRAIT',dpi:300};
  const condition = JSON.stringify(item.condition || {kind:'AND',conditions:[{kind:'QSO_COUNT',operator:'GTE',value:10}]}, null, 2);
  const levels = JSON.stringify(item.levels || [{id:'level-10',name:'10 contacts',threshold:10}], null, 2);
  const actions = item.id ? (item.status === 'DRAFT' || item.status === 'CHANGES_REQUESTED' ? '<button type="button" class="secondary" id="award-submit">Submit for review</button>' : item.status === 'UNDER_REVIEW' ? '<button type="button" class="approve" id="award-approve">Approve</button><button type="button" class="reject" id="award-request-changes">Request changes</button>' : item.status === 'APPROVED' ? '<button type="button" class="primary" id="award-publish">Publish award</button>' : '') : '';
  return `<form id="award-form" class="form-grid"><input type="hidden" id="award-id" value="${esc(item.id || '')}">
    <label>Programme<select id="award-programme" required>${state.programmes.map(p=>`<option value="${esc(p.slug)}" ${p.slug===(item.programmeSlug || state.currentProgramme || state.programmes[0]?.slug)?'selected':''}>${esc(p.name)}</option>`).join('')}</select><small class="field-help">The programme owns this award, its conditions, levels, and publication lifecycle.</small></label>
    <label>Category<select id="award-category"><option value="HUNTER" ${item.category==='HUNTER'?'selected':''}>Hunter</option><option value="ACTIVATOR" ${item.category==='ACTIVATOR'?'selected':''}>Activator</option></select><small class="field-help">Hunter awards measure contacts made with activators; activator awards measure qualifying activation work.</small></label>
    <label>Code<input id="award-code" value="${esc(item.code || '')}" placeholder="SEVILLA-10" required><small class="field-help">A stable programme-owned code used in certificate filenames and historical records.</small></label>
    <label>Name<input id="award-name" value="${esc(item.name || '')}" placeholder="Sevilla starter award" required></label>
    <label class="wide">Description<textarea id="award-description">${esc(item.description || '')}</textarea><small class="field-help">Explain what the participant receives. Detailed eligibility remains in the programme-owned condition below.</small></label>
    <label>Achievement metric<select id="award-metric"><option value="QSO_COUNT" ${item.achievementMetric==='QSO_COUNT'?'selected':''}>QSO count</option><option value="ACTIVATION_COUNT" ${item.achievementMetric==='ACTIVATION_COUNT'?'selected':''}>Activation count</option><option value="UNIQUE_CALLSIGNS" ${item.achievementMetric==='UNIQUE_CALLSIGNS'?'selected':''}>Unique callsigns</option><option value="UNIQUE_ENTITIES" ${item.achievementMetric==='UNIQUE_ENTITIES'?'selected':''}>Unique entities</option></select><small class="field-help">The progress value compared with each level threshold.</small></label>
    <label>Effective from<input id="award-effective" type="datetime-local" value="${esc(item.effectiveFrom ? String(item.effectiveFrom).slice(0,16) : '')}"><small class="field-help">Required when an approved draft is published.</small></label>
    <section class="form-section wide"><div class="section-heading"><div><p class="eyebrow">ELIGIBILITY</p><h3>Programme-owned condition and levels</h3></div><span class="help-badge neutral">AND / OR</span></div><p class="field-help section-intro">Conditions are a small JSON tree so each programme can define its own meaning. Combine child conditions with <code>AND</code>, <code>OR</code>, or <code>NOT</code>; leaf examples include <code>QSO_COUNT</code>, <code>ACTIVATION_COUNT</code>, <code>UNIQUE_CALLSIGNS</code>, <code>UNIQUE_ENTITIES</code>, and programme-defined <code>FIELD</code> values. Levels are an array of thresholds such as 10, 50, and 100.</p><label>Condition JSON<textarea id="award-condition" class="code-editor" required>${esc(condition)}</textarea></label><label>Achievement levels JSON<textarea id="award-levels" class="code-editor" required>${esc(levels)}</textarea></label></section>
    <section class="form-section wide"><div class="section-heading"><div><p class="eyebrow">PRINT ASSET</p><h3>Background image and print profile</h3></div><span class="help-badge">A4 / Letter</span></div><p class="field-help section-intro">At 300 DPI, use 2481 × 3508 px for A4 portrait or 2550 × 3300 px for Letter portrait. Landscape swaps the dimensions. The activity service checks the aspect ratio and minimum resolution before publication.</p><div class="form-grid nested-grid"><label>Background object key<input id="award-background-key" value="${esc(background.objectKey || '')}" placeholder="awards/sevilla/background.png" required></label><label>Media type<input id="award-background-type" value="${esc(background.mediaType || 'image/png')}" required></label><label>Width in pixels<input id="award-background-width" type="number" min="1" value="${esc(background.widthPx || '')}" required></label><label>Height in pixels<input id="award-background-height" type="number" min="1" value="${esc(background.heightPx || '')}" required></label><label>Page<select id="award-page"><option value="A4" ${print.page==='A4'?'selected':''}>A4</option><option value="LETTER" ${print.page==='LETTER'?'selected':''}>Letter</option></select></label><label>Orientation<select id="award-orientation"><option value="PORTRAIT" ${print.orientation==='PORTRAIT'?'selected':''}>Portrait</option><option value="LANDSCAPE" ${print.orientation==='LANDSCAPE'?'selected':''}>Landscape</option></select></label><label>Resolution (DPI)<input id="award-dpi" type="number" min="150" value="${esc(print.dpi || 300)}"></label></div></section>
    <section class="form-section wide"><div class="section-heading"><div><p class="eyebrow">CERTIFICATE DESIGN</p><h3>Position the certificate fields</h3></div><span class="help-badge neutral">WYSIWYG preview</span></div><p class="field-help section-intro">Drag the six required fields on the preview, or fine-tune their normalized positions below. The background image is represented by the registered object key until the renderer loads it.</p>${awardCanvas()}<div id="award-element-rows" class="award-element-list">${awardElementRows()}</div></section>
    <div class="form-actions wide"><button class="primary" type="submit">${item.id ? 'Save award draft' : 'Create award draft'}</button>${actions}</div>${item.status ? `<p class="field-help wide">Current status: <strong>${esc(item.status)}</strong>. Published definitions are immutable; create a new draft for changes.</p>` : ''}</form>`;
}
function setAwardEditor(item = {}) { state.awardSelected = item; $('award-editor').innerHTML = `<div class="panel-heading"><div><p class="eyebrow">AWARD DEFINITION</p><h2>${item.id ? esc(item.name) : 'New award draft'}</h2></div>${item.status ? `<span class="status-pill ${geoStatusClass(item.status)}">${esc(item.status)}</span>` : ''}</div>${awardEditor(item)}`; bindAwardEditor(); bindAwardCanvas(); }
function bindAwardCanvas() { const canvas=$('award-canvas'); if(!canvas)return; canvas.addEventListener('pointerdown',event=>{const element=event.target.closest('[data-award-element]');if(!element)return;state.awardDrag={index:Number(element.dataset.awardElement),x:event.clientX,y:event.clientY};canvas.setPointerCapture(event.pointerId);}); canvas.addEventListener('pointermove',event=>{if(!state.awardDrag)return;const rect=canvas.getBoundingClientRect(),deltaX=(event.clientX-state.awardDrag.x)/rect.width,deltaY=(event.clientY-state.awardDrag.y)/rect.height,element=state.awardTemplateElements[state.awardDrag.index];element.x=Math.max(0,Math.min(1-element.width,element.x+deltaX));element.y=Math.max(0,Math.min(1-element.height,element.y+deltaY));state.awardDrag.x=event.clientX;state.awardDrag.y=event.clientY;const node=canvas.querySelector(`[data-award-element="${state.awardDrag.index}"]`);if(node){node.style.left=`${element.x*100}%`;node.style.top=`${element.y*100}%`;}const fields=document.querySelectorAll(`[data-award-field^="${state.awardDrag.index}:x"],[data-award-field^="${state.awardDrag.index}:y"]`);fields.forEach(field=>field.value=Number(field.dataset.awardField.endsWith(':x')?element.x:element.y).toFixed(2));}); canvas.addEventListener('pointerup',()=>{state.awardDrag=null;}); document.querySelectorAll('[data-award-field]').forEach(field=>field.oninput=()=>{const [index,key]=field.dataset.awardField.split(':');state.awardTemplateElements[Number(index)][key]=Math.max(0,Math.min(1,Number(field.value)||0));const node=canvas.querySelector(`[data-award-element="${index}"]`);if(node){node.style[key==='x'?'left':key==='y'?'top':key==='width'?'width':'height']=`${state.awardTemplateElements[Number(index)][key]*100}%`;}}); }
function awardPayload() { const background={kind:'BACKGROUND',name:$('award-name').value.trim()+' background',objectKey:$('award-background-key').value.trim(),mediaType:$('award-background-type').value.trim(),widthPx:Number($('award-background-width').value),heightPx:Number($('award-background-height').value)}; return {awardId:$('award-id').value||undefined,programmeSlug:$('award-programme').value,code:$('award-code').value.trim(),name:$('award-name').value.trim(),description:$('award-description').value,category:$('award-category').value,achievementMetric:$('award-metric').value,condition:JSON.parse($('award-condition').value),levels:JSON.parse($('award-levels').value),backgroundAsset:background,printSpec:{page:$('award-page').value,orientation:$('award-orientation').value,dpi:Number($('award-dpi').value)},template:{elements:cloneJson(state.awardTemplateElements)}}; }
function bindAwardEditor() { $('award-form').onsubmit=async event=>{event.preventDefault();try{const saved=await api('/v1/awards',{method:'POST',body:JSON.stringify(awardPayload()),headers:{'Idempotency-Key':crypto.randomUUID()}});notify('Award draft saved','success');await loadAwards(saved.id);}catch(error){notify(error.message,'error');}};if($('award-submit'))$('award-submit').onclick=()=>awardAction('submit');if($('award-approve'))$('award-approve').onclick=()=>awardAction('review','APPROVED');if($('award-request-changes'))$('award-request-changes').onclick=()=>awardAction('review','CHANGES_REQUESTED');if($('award-publish'))$('award-publish').onclick=()=>awardAction('publish'); }
async function awardAction(action,decision){try{const id=$('award-id').value;if(!id)return;const body=action==='review'?{decision,reviewerId:state.account.id,note:'Reviewed in award administration'}:action==='publish'?{effectiveFrom:$('award-effective').value,publisherId:state.account.id}:{};if(action==='publish'&&!body.effectiveFrom)throw new Error('Choose an effective date before publishing.');await api(`/v1/awards/${encodeURIComponent(id)}/${action}`,{method:'POST',body:JSON.stringify(body)});notify(action==='publish'?'Award published':`Award ${action}ed`,'success');await loadAwards(id);}catch(error){notify(error.message,'error');}}
 function awardAssetForm() { return `<form id="award-asset-form" class="form-grid"><label>Asset type<select id="asset-kind"><option value="SIGNATURE">Signature</option><option value="BACKGROUND">Background</option></select><small class="field-help">Signature assets are selected when a manager issues a certificate. Backgrounds can be linked in an award definition.</small></label><label>Display name<input id="asset-name" required placeholder="Volker signature"></label><label>Object key<input id="asset-key" required placeholder="signatures/volker.png"></label><label>Media type<input id="asset-type" value="image/png" required></label><label>Width in pixels<input id="asset-width" type="number" min="1" required></label><label>Height in pixels<input id="asset-height" type="number" min="1" required></label><label class="wide">Image file<input id="asset-file" type="file" accept="image/*"><small class="field-help">The file is uploaded to SeaweedFS through a short-lived S3 URL when available. The metadata can also be registered first.</small></label><label class="wide">SHA-256 checksum<input id="asset-sha" placeholder="Optional integrity checksum"><small class="field-help">The binary is stored in SeaweedFS or another S3-compatible store; this page registers its provenance and dimensions.</small></label><div class="form-actions wide"><button class="primary" type="submit">Register image asset</button></div></form>`; }
async function uploadAssetFile(asset,file){if(!file)return;try{const upload=await api(`/v1/awards/assets/${encodeURIComponent(asset.id)}/upload-url`,{method:'POST',body:'{}'});const response=await fetch(upload.url,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});if(!response.ok)throw new Error('direct object upload failed');notify('Image asset registered and uploaded','success');return;}catch(_){if(file.size>700000)throw new Error('Asset metadata was saved, but this file is too large for the API fallback upload. Configure a browser-reachable SeaweedFS endpoint.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';bytes.forEach(value=>binary+=String.fromCharCode(value));await api(`/v1/awards/assets/${encodeURIComponent(asset.id)}/content`,{method:'POST',body:JSON.stringify({contentBase64:btoa(binary)})});notify('Image asset registered and uploaded','success');}}
async function registerAwardAsset(event){event.preventDefault();try{const asset=await api('/v1/awards/assets',{method:'POST',body:JSON.stringify({kind:$('asset-kind').value,name:$('asset-name').value.trim(),objectKey:$('asset-key').value.trim(),mediaType:$('asset-type').value.trim(),widthPx:Number($('asset-width').value),heightPx:Number($('asset-height').value),sha256:$('asset-sha').value.trim()||undefined}),headers:{'Idempotency-Key':crypto.randomUUID()}});await uploadAssetFile(asset,$('asset-file').files[0]);if(!$('asset-file').files[0])notify('Image asset metadata registered','success');await loadAwardAssets();$('award-asset-form').reset();$('asset-type').value='image/png';}catch(error){notify(error.message,'error');}}
async function loadAwardAssets(){try{const data=await api('/v1/awards/assets?pageSize=100');state.awardAssets=data.items||[];$('award-assets').innerHTML=state.awardAssets.map(asset=>`<div class="table-row"><span><strong>${esc(asset.name)}</strong><small>${esc(asset.kind)} · ${esc(asset.objectKey)}</small></span><span>${esc(asset.widthPx)} × ${esc(asset.heightPx)} px</span><span class="muted">${esc(asset.bucket)}</span></div>`).join('')||'<p class="muted empty">No image assets registered.</p>';}catch(error){$('award-assets').innerHTML=`<div class="error-card">${esc(error.message)}</div>`;}}
async function loadAwardRequests(){try{const data=await api('/v1/awards/requests?pageSize=100');$('award-requests').innerHTML=(data.items||[]).map(request=>`<div class="table-row"><span><strong>${esc(request.callsign)} · ${esc(request.personName)}</strong><small>${esc(request.programmeSlug)} · ${esc(request.category)} · level ${esc(request.levelId)}</small></span><span class="status-pill ${geoStatusClass(request.status)}">${esc(request.status)}</span><small>${esc(request.requestedAt||'')}</small></div>`).join('')||'<p class="muted empty">No award requests yet.</p>';}catch(error){$('award-requests').innerHTML=`<div class="error-card">${esc(error.message)}</div>`;}}
async function loadAwardIssuances(){try{const data=await api('/v1/awards/issuances?pageSize=100');$('award-issuances').innerHTML=(data.items||[]).map(issuance=>`<div class="table-row"><span><strong>${esc(issuance.awardName)}</strong><small>${esc(issuance.callsign)} · ${esc(issuance.personName)} · ${esc(issuance.levelId)}</small></span><span>${esc(issuance.dateObtained)}</span><span class="muted">${issuance.artifact?.downloadReady?'Download ready':'Render queued'}</span></div>`).join('')||'<p class="muted empty">No certificates issued yet.</p>';}catch(error){$('award-issuances').innerHTML=`<div class="error-card">${esc(error.message)}</div>`;}}
async function renderAwards(){const view=$('awards-view');view.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ACTIVITY & CERTIFICATES</p><h1>Awards and certificates</h1><p class="muted">Programme-owned hunter and activator awards use the same activity API and service port as activations and QSOs.</p></div><button class="primary" id="award-new">New award draft</button></div><div class="toolbar"><label class="toolbar-field">Programme ${programmeChooser('award-programme-filter')}</label><button class="secondary" id="award-refresh">Refresh</button></div><div class="split-layout"><article class="panel"><div class="panel-heading"><div><h2>Award definitions</h2><small class="muted">Draft → review → explicit publication with an effective date.</small></div></div><div id="award-list" class="table-list"></div></article><article class="panel" id="award-editor"><div class="panel-heading"><h2>New award draft</h2></div>${awardEditor()}</article></div><div class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h2>Signature and background assets</h2><small class="muted">Register the image metadata for SeaweedFS or another S3-compatible store.</small></div></div>${awardAssetForm()}<div id="award-assets" class="table-list"></div></article><article class="panel"><div class="panel-heading"><div><h2>Requests and issuances</h2><small class="muted">Issuances are permanent records; higher levels create separate requests.</small></div></div><div id="award-requests" class="table-list"></div><div class="subsection-heading"><h3>Issued certificates</h3></div><div id="award-issuances" class="table-list"></div></article></div>`;$('award-programme-filter').onchange=()=>{state.currentProgramme=$('award-programme-filter').value;loadAwards();};$('award-refresh').onclick=()=>loadAwards();$('award-new').onclick=()=>setAwardEditor();$('award-asset-form').onsubmit=registerAwardAsset;bindAwardEditor();bindAwardCanvas();await Promise.all([loadAwards(),loadAwardAssets(),loadAwardRequests(),loadAwardIssuances()]);}
async function loadAwards(selectedId){const slug=$('award-programme-filter')?.value||state.currentProgramme||state.programmes[0]?.slug;const query=slug?`?programme=${encodeURIComponent(slug)}&pageSize=100`:'?pageSize=100';try{const data=await api(`/v1/awards${query}`);state.awardItems=data.items||[];$('award-list').innerHTML=state.awardItems.map(item=>`<button class="table-row" data-award-id="${esc(item.id)}"><span><strong>${esc(item.name)}</strong><small>${esc(item.programmeSlug)} · ${esc(item.category)} · ${esc(item.code)}</small></span><span class="status-pill ${geoStatusClass(item.status)}">${esc(item.status)}</span></button>`).join('')||'<p class="muted empty">No awards are configured for this programme.</p>';document.querySelectorAll('[data-award-id]').forEach(button=>button.onclick=()=>setAwardEditor(state.awardItems.find(item=>item.id===button.dataset.awardId)));if(selectedId){const existing=state.awardItems.find(item=>item.id===selectedId);if(existing)setAwardEditor(existing);} }catch(error){$('award-list').innerHTML=`<div class="error-card">${esc(error.message)}</div>`;}}
async function renderActivity() { const view=$('activity-view'); view.innerHTML=`<div class="page-heading"><div><p class="eyebrow">OPERATIONS</p><h1>Activity</h1><p class="muted">Protected activation and QSO operational view.</p></div><button class="secondary" id="activity-refresh">Refresh</button></div><article class="panel"><div id="activity-table" class="table-list"></div></article>`; $('activity-refresh').onclick=renderActivity; try { const data=await api('/v1/activations?pageSize=100'); $('activity-table').innerHTML=(data.items||[]).map(a=>`<div class="table-row"><span><strong>${esc(a.id.slice(0,8))}…</strong><small>${esc(a.programmeSlug)} · ${esc(a.entityId)} · ${esc(a.operatorId)}</small></span><span class="status-pill ${a.status==='OPEN'?'proposed':'approved'}">${esc(a.status)}</span><span>${esc(a.qsos?.length||0)} QSOs</span></div>`).join('')||'<p class="muted empty">No activations recorded.</p>'; } catch(error) { $('activity-table').innerHTML=`<div class="error-card">${esc(error.message)}</div>`; } }
