function programmeChooser(id) { return `<select id="${id}">${state.programmes.map(p=>`<option value="${esc(p.slug)}" ${p.slug === (state.currentProgramme || state.programmes[0]?.slug) ? 'selected' : ''}>${esc(p.name)}</option>`).join('')}</select>`; }
function contentEditor(item = {}) {
  const effective = item.effectiveFrom ? String(item.effectiveFrom).slice(0,16) : '';
  const actions = item.id ? (item.status === 'DRAFT' || item.status === 'CHANGES_REQUESTED' ? '<button type="button" class="secondary" id="content-submit">Submit for review</button>' : item.status === 'UNDER_REVIEW' ? '<button type="button" class="approve" id="content-approve">Approve</button><button type="button" class="reject" id="content-request-changes">Request changes</button>' : item.status === 'APPROVED' ? '<button type="button" class="primary" id="content-publish">Publish</button>' : '') : '';
  return `<form id="content-form" class="form-grid"><input type="hidden" id="content-id" value="${esc(item.id || '')}"><label>Content key<input id="content-key" value="${esc(item.key || '')}" placeholder="programme.welcome" required><small class="field-help">A stable name used by the public application. Keep it unchanged after publication.</small></label><label>Locale<input id="content-locale" value="${esc(item.locale || 'en')}" placeholder="en" required><small class="field-help">Use the programme’s locale code, such as en or es.</small></label><label>Fallback locale<input id="content-fallback" value="${esc(item.fallbackLocale || '')}" placeholder="en"><small class="field-help">Optional locale to use when this translation is missing or unpublished.</small></label><label>Effective from<input id="content-effective" type="datetime-local" value="${esc(effective)}"><small class="field-help">Publishing requires an explicit effective date.</small></label><label class="wide">Text or content value<textarea id="content-value" required>${esc(item.value || '')}</textarea><small class="field-help">Programme-owned content. The platform stores it without imposing a message catalogue.</small></label><div class="form-actions wide"><button class="primary" type="submit">${item.id ? 'Save draft' : 'Create draft'}</button>${actions}</div>${item.status ? `<p class="field-help wide">Current status: <strong>${esc(item.status)}</strong>. Drafts can be edited; published content is immutable and should be superseded by a new draft.</p>` : ''}</form>`;
}
function setContentEditor(item = {}) { state.contentSelected = item; $('content-editor').innerHTML = `<div class="panel-heading"><div><p class="eyebrow">CONTENT VERSION</p><h2>${item.id ? esc(item.key) : 'New content draft'}</h2></div>${item.status ? `<span class="status-pill ${geoStatusClass(item.status)}">${esc(item.status)}</span>` : ''}</div>${contentEditor(item)}`; bindContentEditor(); }
function bindContentEditor() {
  $('content-form').onsubmit = async event => { event.preventDefault(); try { const slug = $('content-programme').value; const body = {contentId:$('content-id').value || undefined, key:$('content-key').value.trim(), locale:$('content-locale').value.trim(), fallbackLocale:$('content-fallback').value.trim() || null, value:$('content-value').value}; const saved = await api(`/v1/programmes/${encodeURIComponent(slug)}/content`, {method:'POST',body:JSON.stringify(body)}); notify('Content draft saved','success'); await loadContentAdmin(saved.id); } catch(error) { notify(error.message,'error'); } };
  if ($('content-submit')) $('content-submit').onclick = () => contentAction('submit');
  if ($('content-approve')) $('content-approve').onclick = () => contentAction('review', 'APPROVED');
  if ($('content-request-changes')) $('content-request-changes').onclick = () => contentAction('review', 'CHANGES_REQUESTED');
  if ($('content-publish')) $('content-publish').onclick = () => contentAction('publish');
}
async function contentAction(action, decision) { try { const slug=$('content-programme').value, id=$('content-id').value; if (!id) return; const note=$('content-review-note')?.value || ''; let path=`/v1/programmes/${encodeURIComponent(slug)}/content/${encodeURIComponent(id)}/${action}`; const body=action==='review'?{decision,reviewerId:state.account.id,note}:action==='publish'?{effectiveFrom:$('content-effective').value,publisherId:state.account.id}:{}; if(action==='publish'&&!body.effectiveFrom) throw new Error('Choose an effective date before publishing.'); await api(path,{method:'POST',body:JSON.stringify(body)}); notify(action==='publish'?'Content published':`Content ${action}ed`,'success'); await loadContentAdmin(id); } catch(error) { notify(error.message,'error'); } }
async function renderContent() { const view=$('content-view'); view.innerHTML=`<div class="page-heading"><div><p class="eyebrow">CONTENT OPERATIONS</p><h1>Content & translations</h1><p class="muted">Programme-owned text follows a draft, review, publish lifecycle. Published locales and fallback coverage are visible at a glance.</p></div><button class="primary" id="content-new">New content draft</button></div><div class="toolbar"><label class="toolbar-field">Programme ${programmeChooser('content-programme')}</label><button class="secondary" id="content-refresh">Refresh</button></div><article class="panel"><div class="panel-heading"><div><h2>Locale coverage</h2><small class="muted">Coverage counts published keys only; drafts remain visible in the content list.</small></div></div><div id="content-coverage" class="coverage-grid"></div></article><div class="split-layout"><article class="panel"><div class="panel-heading"><h2>Content versions</h2></div><div id="content-list" class="table-list"></div></article><article class="panel" id="content-editor"><div class="panel-heading"><h2>New content draft</h2></div>${contentEditor()}</article></div>`; $('content-programme').onchange=()=>{state.currentProgramme=$('content-programme').value;loadContentAdmin();}; $('content-refresh').onclick=()=>loadContentAdmin(); $('content-new').onclick=()=>setContentEditor(); bindContentEditor(); await loadContentAdmin(); }
async function loadContentAdmin(selectedId) { const slug=$('content-programme')?.value || state.currentProgramme || state.programmes[0]?.slug; if(!slug)return; try { const [data,coverage]=await Promise.all([api(`/v1/programmes/${encodeURIComponent(slug)}/content?pageSize=100`),api(`/v1/programmes/${encodeURIComponent(slug)}/content/coverage`)]); state.contentItems=data.items||[]; $('content-coverage').innerHTML=(coverage.locales||[]).map(locale=>`<div class="coverage-card"><strong>${esc(locale.locale)}</strong><span>${esc(locale.coveragePercent)}%</span><small>${esc(locale.published)} of ${esc(locale.total)} published${locale.missingKeys?.length?` · missing: ${esc(locale.missingKeys.join(', '))}`:''}</small></div>`).join('')||'<p class="muted empty">No content keys yet.</p>'; $('content-list').innerHTML=state.contentItems.map(item=>`<button class="table-row" data-content-id="${esc(item.id)}"><span><strong>${esc(item.key)}</strong><small>${esc(item.locale)}${item.fallbackLocale?` · fallback ${esc(item.fallbackLocale)}`:''}</small></span><span class="status-pill ${geoStatusClass(item.status)}">${esc(item.status)}</span></button>`).join('')||'<p class="muted empty">No content drafts yet.</p>'; document.querySelectorAll('[data-content-id]').forEach(button=>button.onclick=()=>setContentEditor(state.contentItems.find(item=>item.id===button.dataset.contentId))); if(selectedId) setContentEditor(state.contentItems.find(item=>item.id===selectedId)||{}); } catch(error) { $('content-list').innerHTML=`<div class="error-card">${esc(error.message)}</div>`; } }
