function geoVertexRefs(geometry) {
  if (!geometry || !geometry.coordinates) return [];
  if (geometry.type === 'Point') return [{get: () => geometry.coordinates, set: value => { geometry.coordinates = value; }}];
  if (geometry.type === 'Polygon') return (geometry.coordinates[0] || []).map((_, index) => ({get: () => geometry.coordinates[0][index], set: value => { geometry.coordinates[0][index] = value; if (index === 0 && geometry.coordinates[0].length > 1) geometry.coordinates[0][geometry.coordinates[0].length - 1] = value; }}));
  if (geometry.type === 'MultiPolygon') return (geometry.coordinates[0]?.[0] || []).map((_, index) => ({get: () => geometry.coordinates[0][0][index], set: value => { geometry.coordinates[0][0][index] = value; if (index === 0 && geometry.coordinates[0][0].length > 1) geometry.coordinates[0][0][geometry.coordinates[0][0].length - 1] = value; }}));
  return [];
}
function geoBounds(entities) {
  const coords = entities.flatMap(entity => geoVertexRefs(entity.geometry).map(ref => ref.get())).filter(coord => Array.isArray(coord) && coord.length >= 2);
  if (!coords.length) return {minLon:-3.75,maxLon:-3.65,minLat:40.38,maxLat:40.46};
  const lons = coords.map(coord => Number(coord[0])), lats = coords.map(coord => Number(coord[1]));
  const minLon = Math.min(...lons), maxLon = Math.max(...lons), minLat = Math.min(...lats), maxLat = Math.max(...lats);
  const lonPad = Math.max((maxLon - minLon) * .18, .01), latPad = Math.max((maxLat - minLat) * .18, .01);
  return {minLon:minLon-lonPad,maxLon:maxLon+lonPad,minLat:minLat-latPad,maxLat:maxLat+latPad};
}
function geoProject(coord, bounds) { return [24 + ((Number(coord[0]) - bounds.minLon) / (bounds.maxLon - bounds.minLon)) * 552, 336 - ((Number(coord[1]) - bounds.minLat) / (bounds.maxLat - bounds.minLat)) * 312]; }
function geoUnproject(x, y, bounds) { return [bounds.minLon + ((x - 24) / 552) * (bounds.maxLon - bounds.minLon), bounds.minLat + ((336 - y) / 312) * (bounds.maxLat - bounds.minLat)]; }
function geoShapeMarkup(entity, bounds, selected) {
  const refs = geoVertexRefs(selected && state.geoEditingGeometry ? state.geoEditingGeometry : entity.geometry);
  const projected = refs.map(ref => geoProject(ref.get(), bounds));
  const shape = entity.geometry?.type === 'Point' ? `<circle data-geo-shape="${esc(entity.id)}" cx="${projected[0]?.[0] || 0}" cy="${projected[0]?.[1] || 0}" r="${selected ? 9 : 7}" class="geo-shape-point"/>` : `<polygon data-geo-shape="${esc(entity.id)}" points="${projected.map(point => point.join(',')).join(' ')}" class="geo-shape-polygon"/>`;
  const handles = selected && state.geoEditingGeometry && refs.length ? projected.map((point, index) => `<circle data-vertex="${index}" cx="${point[0]}" cy="${point[1]}" r="6" class="geo-vertex"/>`).join('') : '';
  return `<g data-geo-id="${esc(entity.id)}" class="geo-layer ${geoStatusClass(entity.status)} ${selected ? 'selected' : ''}">${shape}${handles}<text x="${(projected[0]?.[0] || 30) + 10}" y="${(projected[0]?.[1] || 30) - 10}" class="geo-label">${esc(entity.name)}</text></g>`;
}
function renderGeoMap() {
  const map = $('geo-map'); if (!map) return;
  const visible = state.geoEntities.filter(entity => !$(`layer-${geoStatusClass(entity.status)}`) || $(`layer-${geoStatusClass(entity.status)}`).checked);
  state.geoMapBounds = geoBounds(visible.length ? visible : state.geoEntities);
  const layers = visible.map(entity => geoShapeMarkup(entity, state.geoMapBounds, state.geoSelected?.id === entity.id)).join('');
  map.innerHTML = `<svg id="geo-svg" viewBox="0 0 600 360" role="img" aria-label="Geodata review map"><rect width="600" height="360" class="geo-water"/><path d="M0 60H600M0 120H600M0 180H600M0 240H600M0 300H600M100 0V360M200 0V360M300 0V360M400 0V360M500 0V360" class="geo-grid"/>${layers || '<text x="220" y="180" class="geo-empty">No entities in these layers</text>'}</svg>`;
  document.querySelectorAll('[data-geo-id]').forEach(node => node.onclick = event => { if (!event.target.dataset.vertex) selectGeoEntity(node.dataset.geoId); });
  const svg = $('geo-svg'); let dragging = null;
  svg?.addEventListener('pointerdown', event => { const handle = event.target.closest('[data-vertex]'); if (!handle || !state.geoEditingGeometry) return; dragging = {index:Number(handle.dataset.vertex)}; svg.setPointerCapture(event.pointerId); });
  svg?.addEventListener('pointermove', event => { if (!dragging) return; const rect = svg.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width) * 600, y = ((event.clientY - rect.top) / rect.height) * 360; const refs = geoVertexRefs(state.geoEditingGeometry); refs[dragging.index]?.set(geoUnproject(x, y, state.geoMapBounds)); const selectedShape = svg.querySelector('[data-geo-shape]'); if (selectedShape) { const refsNow = geoVertexRefs(state.geoEditingGeometry), points = refsNow.map(ref => geoProject(ref.get(), state.geoMapBounds)); if (state.geoEditingGeometry.type === 'Point') { selectedShape.setAttribute('cx', points[0][0]); selectedShape.setAttribute('cy', points[0][1]); } else selectedShape.setAttribute('points', points.map(point => point.join(',')).join(' ')); svg.querySelectorAll('[data-vertex]').forEach((vertex, index) => { vertex.setAttribute('cx', points[index][0]); vertex.setAttribute('cy', points[index][1]); }); } });
  svg?.addEventListener('pointerup', () => { dragging = null; });
}
async function renderGeoReview() {
  const view = $('geodata-view');
  view.innerHTML = `<div class="page-heading"><div><p class="eyebrow">POSTGIS WORKFLOW</p><h1>Map-based geodata review</h1><p class="muted">Compare source data, edit geometry, and record an auditable decision for each lifecycle layer.</p></div><button class="primary" id="geo-refresh">Refresh map</button></div><div class="toolbar"><select id="geo-programme"><option value="">All programmes</option>${state.programmes.map(p=>`<option value="${esc(p.slug)}">${esc(p.name)}</option>`).join('')}</select><button type="button" class="secondary" id="geo-import-toggle">Import GeoJSON</button></div><div class="geo-layout"><aside class="panel geo-sidebar"><div class="panel-heading"><div><h2>Layers</h2><small class="muted">Verified and candidate data stay visually distinct.</small></div><span id="geo-count" class="muted"></span></div><label class="layer-toggle candidate"><input id="layer-candidate" type="checkbox" checked> Candidate</label><label class="layer-toggle proposed"><input id="layer-proposed" type="checkbox" checked> Proposed</label><label class="layer-toggle approved"><input id="layer-approved" type="checkbox" checked> Approved</label><label class="layer-toggle rejected"><input id="layer-rejected" type="checkbox"> Rejected</label><div id="geo-entity-list" class="table-list geo-entity-list"></div></aside><section class="geo-center"><div id="geo-map" class="geo-map"></div><article id="geo-inspector" class="panel"><p class="muted empty">Select an entity on the map or in the list to inspect its source, geometry, notes, and audit history.</p></article></section></div><div id="geo-import" class="panel" hidden><div class="panel-heading"><h2>Manual import</h2><span class="muted">Imported features enter as candidates.</span></div><form id="geo-import-form" class="form-grid"><label>Programme<select id="import-programme">${state.programmes.map(p=>`<option value="${esc(p.slug)}">${esc(p.name)}</option>`).join('')}</select></label><label>Source name<input id="import-source" value="Manual administration import" required></label><label class="wide">GeoJSON feature collection<textarea id="import-features" required>{"type":"FeatureCollection","features":[]}</textarea></label><div class="form-actions wide"><button type="submit" class="primary">Queue import</button></div></form></div>`;
  $('geo-refresh').onclick = loadGeoReview; $('geo-import-toggle').onclick = () => { $('geo-import').hidden = !$('geo-import').hidden; }; ['candidate','proposed','approved','rejected'].forEach(status => $(`layer-${status}`).onchange = renderGeoMap); $('geo-programme').onchange = loadGeoReview; $('geo-import-form').onsubmit = submitImport; await loadGeoReview();
}
async function loadGeoReview() { const query = new URLSearchParams({pageSize:'100'}); if ($('geo-programme')?.value) query.set('programme', $('geo-programme').value); try { const data = await api(`/v1/geodata/entities?${query}`); state.geoEntities = data.items || []; $('geo-count').textContent = `${data.total} entities`; $('geo-entity-list').innerHTML = state.geoEntities.map(entity => `<button class="table-row geo-entity-row ${state.geoSelected?.id===entity.id?'selected':''}" data-select-geo="${esc(entity.id)}"><span><strong>${esc(entity.name)}</strong><small>${esc(entity.entityType)} · ${esc(entity.provenance?.adapter || 'manual')}</small></span><span class="status-pill ${geoStatusClass(entity.status)}">${esc(entity.status)}</span></button>`).join('') || '<p class="muted empty">No geodata entities match.</p>'; document.querySelectorAll('[data-select-geo]').forEach(button => button.onclick = () => selectGeoEntity(button.dataset.selectGeo)); if (!state.geoSelected || !state.geoEntities.some(entity => entity.id === state.geoSelected.id)) { state.geoSelected = state.geoEntities[0] || null; state.geoEditingGeometry = cloneJson(state.geoSelected?.geometry); } renderGeoMap(); if (state.geoSelected) await selectGeoEntity(state.geoSelected.id); } catch (error) { $('geo-entity-list').innerHTML = `<div class="error-card">${esc(error.message)}</div>`; } }
async function selectGeoEntity(id) { state.geoSelected = state.geoEntities.find(entity => entity.id === id) || null; state.geoEditingGeometry = cloneJson(state.geoSelected?.geometry); renderGeoMap(); const entity = state.geoSelected; if (!entity) return; const audit = await api(`/v1/geodata/entities/${encodeURIComponent(id)}/audit`); $('geo-inspector').innerHTML = `<div class="panel-heading"><div><p class="eyebrow">ENTITY INSPECTOR</p><h2>${esc(entity.name)}</h2><p class="muted">${esc(entity.programmeSlug)} · ${esc(entity.entityType)} · ${esc(entity.status)}</p></div><span class="status-pill ${geoStatusClass(entity.status)}">${esc(entity.status)}</span></div><div class="inspector-grid"><section><h3>Source comparison</h3><p class="field-help">The imported source snapshot is shown beside the current platform geometry. Editing creates a history entry; it never changes the original provenance.</p><div class="compare-grid"><div><small class="muted">Source snapshot</small><pre class="data-preview">${esc(JSON.stringify(entity.provenance?.sourceFeature || entity.provenance?.source || {}, null, 2))}</pre></div><div><small class="muted">Current platform geometry</small><pre class="data-preview">${esc(JSON.stringify(entity.geometry || {}, null, 2))}</pre></div></div></section><section><h3>Geometry editing</h3><p class="field-help">Drag the blue vertices on the map. Point entities can be moved; polygon vertices can be adjusted. Save only after checking the source comparison.</p><label>Geometry change note<textarea id="geo-geometry-note" placeholder="Explain why the geometry was adjusted"></textarea></label><button class="secondary" id="geo-save-geometry">Save geometry</button></section></div><section><h3>Review decision</h3><label>Review note<textarea id="geo-review-note" placeholder="Record the evidence or reason for this decision"></textarea></label><div class="form-actions">${entity.status==='CANDIDATE'?'<button class="secondary" id="geo-propose">Propose for review</button>':''}${entity.status==='PROPOSED'?'<button class="approve" id="geo-approve">Approve</button><button class="reject" id="geo-reject">Reject</button>':''}</div></section><section><h3>Audit history</h3><div class="audit-list">${[...(audit.reviewHistory||[]),...(audit.geometryHistory||[])].sort((a,b)=>String(b.occurredAt||b.editedAt).localeCompare(String(a.occurredAt||a.editedAt))).map(item=>`<div class="audit-row"><strong>${esc(item.action || 'GEOMETRY_EDIT')}</strong><span>${esc(item.occurredAt || item.editedAt || '')}</span><small>${esc(item.note || item.reviewerId || item.editorId || '')}</small></div>`).join('') || '<p class="muted">No audit entries yet.</p>'}</div></section>`; $('geo-save-geometry').onclick = saveGeoGeometry; if ($('geo-propose')) $('geo-propose').onclick = () => reviewGeoEntity('PROPOSE'); if ($('geo-approve')) $('geo-approve').onclick = () => reviewGeoEntity('APPROVED'); if ($('geo-reject')) $('geo-reject').onclick = () => reviewGeoEntity('REJECTED'); }
async function saveGeoGeometry() { try { await api(`/v1/geodata/entities/${encodeURIComponent(state.geoSelected.id)}/geometry`, {method:'POST', body:JSON.stringify({geometry:state.geoEditingGeometry, editorId:state.account.id, note:$('geo-geometry-note').value}), headers:{'Idempotency-Key':crypto.randomUUID()}}); notify('Geometry saved with audit history','success'); await loadGeoReview(); } catch (error) { notify(error.message,'error'); } }
async function reviewGeoEntity(decision) { try { const note = $('geo-review-note').value; if (decision === 'PROPOSE') await api(`/v1/geodata/entities/${encodeURIComponent(state.geoSelected.id)}/propose`, {method:'POST',body:JSON.stringify({proposerId:state.account.id,note}),headers:{'Idempotency-Key':crypto.randomUUID()}}); else await api(`/v1/geodata/entities/${encodeURIComponent(state.geoSelected.id)}/review`, {method:'POST',body:JSON.stringify({decision,reviewerId:state.account.id,note}),headers:{'Idempotency-Key':crypto.randomUUID()}}); notify(decision === 'PROPOSE' ? 'Entity proposed for review' : `Entity ${decision.toLowerCase()}`,'success'); await loadGeoReview(); } catch(error) { notify(error.message,'error'); } }
