<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue';
import { apiRequest } from '../lib/api';
import { myotaClient } from '../lib/myotaClient';
import { useAppStore } from '../stores/app';
import { utcInput, utcInputValue } from '../lib/utc';
interface ContentItem { id?: string; key: string; locale: string; fallbackLocale?: string; value: string; status?: string; effectiveFrom?: string; }
const store = useAppStore(); const programme = ref(store.currentProgramme || store.programmes[0]?.slug || ''); const items = ref<ContentItem[]>([]); const coverage = ref<any[]>([]); const selected = ref<ContentItem | null>(null); const message = ref('');
const form = reactive({ key: '', locale: 'en', fallbackLocale: '', value: '', effectiveFrom: '' });
function edit(item: ContentItem | null): void { selected.value = item; Object.assign(form, { key: item?.key || '', locale: item?.locale || 'en', fallbackLocale: item?.fallbackLocale || '', value: item?.value || '', effectiveFrom: utcInput(item?.effectiveFrom) }); }
async function load(selectedId?: string | Event): Promise<void> { if (!programme.value) return; const id = typeof selectedId === 'string' ? selectedId : undefined; const [data, coverageData] = await Promise.all([apiRequest<{ items: ContentItem[] }>(`/v1/programmes/${encodeURIComponent(programme.value)}/content?pageSize=100`), apiRequest<{ locales: any[] }>(`/v1/programmes/${encodeURIComponent(programme.value)}/content/coverage`)]); items.value = data.items || []; coverage.value = coverageData.locales || []; if (id) edit(items.value.find(item => item.id === id) || null); }
async function save(): Promise<void> { try { const saved = await apiRequest<ContentItem>(`/v1/programmes/${encodeURIComponent(programme.value)}/content`, { method: 'POST', body: JSON.stringify({ contentId: selected.value?.id, key: form.key.trim(), locale: form.locale.trim(), fallbackLocale: form.fallbackLocale.trim() || null, value: form.value }) }); message.value = 'Content draft saved.'; await load(saved.id); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to save content.'; } }
async function action(actionName: string, decision?: string): Promise<void> { if (!selected.value?.id) return; try { if (actionName === 'publish' && !form.effectiveFrom) throw new Error('Choose an effective date before publishing.'); const body = actionName === 'review' ? { status: decision, reviewerId: store.account?.id } : actionName === 'publish' ? { status: 'PUBLISHED', effectiveFrom: utcInputValue(form.effectiveFrom, selected.value?.effectiveFrom), publisherId: store.account?.id } : { status: 'UNDER_REVIEW', submitterId: store.account?.id }; await myotaClient.patchProgrammeContent(programme.value, selected.value.id, body); message.value = `Content ${actionName === 'publish' ? 'published' : `${actionName}ed`}.`; await load(selected.value.id); } catch (error) { message.value = error instanceof Error ? error.message : 'Content action failed.'; } }
watch(programme, () => { store.currentProgramme = programme.value; load(); }); onMounted(() => load());
</script>

<template>
  <section class="page-heading"><div><p class="eyebrow">CONTENT OPERATIONS</p><h1>Content & translations</h1><p class="muted">Programme-owned content follows a draft, review, publish lifecycle with locale fallback.</p></div><button class="primary" @click="edit(null)">New content draft</button></section>
  <div class="toolbar"><label class="toolbar-field">Programme<select v-model="programme"><option v-for="item in store.programmes" :key="item.slug" :value="item.slug">{{ item.name }}</option></select></label><button class="secondary" @click="load">Refresh</button></div>
  <div v-if="message" class="notice" role="status">{{ message }}</div>
  <article class="panel"><div class="panel-heading"><div><h2>Locale coverage</h2><small class="muted">Published keys only; drafts remain visible below.</small></div></div><div class="coverage-grid"><div v-for="locale in coverage" :key="locale.locale" class="coverage-card"><strong>{{ locale.locale }}</strong><span>{{ locale.coveragePercent }}%</span><small>{{ locale.published }} of {{ locale.total }} published</small></div><p v-if="!coverage.length" class="muted empty">No content keys yet.</p></div></article>
  <div class="split-layout"><article class="panel"><div class="panel-heading"><h2>Content versions</h2></div><div class="table-list"><button v-for="item in items" :key="item.id" class="table-row" :class="{ selected: selected?.id === item.id }" @click="edit(item)"><span><strong>{{ item.key }}</strong><small>{{ item.locale }}<span v-if="item.fallbackLocale"> · fallback {{ item.fallbackLocale }}</span></small></span><span class="status-pill" :class="(item.status || '').toLowerCase()">{{ item.status }}</span></button><p v-if="!items.length" class="muted empty">No content drafts yet.</p></div></article><article class="panel"><div class="panel-heading"><h2>{{ selected ? selected.key : 'New content draft' }}</h2></div><form class="form-grid" @submit.prevent="save"><label>Content key<input v-model="form.key" required></label><label>Locale<input v-model="form.locale" required></label><label>Fallback locale<input v-model="form.fallbackLocale"></label><label>Effective from (UTC)<input v-model="form.effectiveFrom" type="datetime-local"></label><label class="wide">Text or content value<textarea v-model="form.value" required></textarea></label><div class="form-actions wide"><button class="primary" type="submit">Save draft</button><button v-if="selected && ['DRAFT','CHANGES_REQUESTED'].includes(selected.status || '')" class="secondary" type="button" @click="action('submit')">Submit for review</button><button v-if="selected?.status === 'UNDER_REVIEW'" class="approve" type="button" @click="action('review', 'APPROVED')">Approve</button><button v-if="selected?.status === 'UNDER_REVIEW'" class="reject" type="button" @click="action('review', 'CHANGES_REQUESTED')">Request changes</button><button v-if="selected?.status === 'APPROVED'" class="primary" type="button" @click="action('publish')">Publish</button></div></form></article></div>
</template>
