<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { apiRequest } from '../lib/api';
import { useAppStore } from '../stores/app';
import LeafletMap from '../components/LeafletMap.vue';
import type { EntityCategory, GeoEntity } from '../types';

const props = defineProps<{ mode: 'review' | 'management' }>();
const store = useAppStore();
const entities = ref<GeoEntity[]>([]); const categories = ref<EntityCategory[]>([]); const selected = ref<GeoEntity | null>(null); const selectedIds = ref<string[]>([]); const total = ref(0); const page = ref(1); const pageSize = ref(25); const loading = ref(false); const error = ref(''); const message = ref(''); const audit = ref<unknown[]>([]);
const statuses = ['CANDIDATE', 'APPROVED', 'RETIRED', 'REJECTED'];
const filters = reactive({ programme: '', status: [] as string[], entityType: '', continent: '', country: '', region: '', province: '', city: '' });
const editName = ref(''); const editNote = ref(''); const geometryNote = ref(''); const geometryJson = ref(''); const editTypes = ref<string[]>([]); const geometryType = ref('');
const creating = ref(false); const newName = ref(''); const newTypes = ref<string[]>([]); const newGeometry = ref('{\n  "type": "Point",\n  "coordinates": [-5.99, 37.39]\n}');
const isManagement = computed(() => props.mode === 'management'); const allSelected = computed(() => entities.value.length > 0 && entities.value.every(item => selectedIds.value.includes(item.id))); const isGlobalAdmin = computed(() => (store.account?.roles || []).some(role => role.role === 'GLOBAL_OPERATOR' || role.scopes?.includes('*')));
const selectedStatusOptions = computed(() => selected.value?.status === 'APPROVED' ? ['RETIRED'] : statuses);
const title = computed(() => isManagement.value ? 'Entity management' : 'Geodata review');

function setError(value: unknown): void { error.value = value instanceof Error ? value.message : String(value); }
function categoryCodes(entity: GeoEntity): string[] { return (entity.entityTypes || (entity.entityType ? [entity.entityType] : [])).map(item => typeof item === 'string' ? item : item.code); }
function locationValue(entity: GeoEntity, key: string): string { return String(entity.location?.[key] || ''); }
function query(): string { const params = new URLSearchParams({ page: String(page.value), pageSize: String(pageSize.value) }); if (filters.programme) params.set('programme', filters.programme); if (filters.status.length) params.set('status', filters.status.join(',')); if (filters.entityType) params.set('entityType', filters.entityType); for (const key of ['continent', 'country', 'region', 'province', 'city']) { const value = filters[key as keyof typeof filters]; if (typeof value === 'string' && value) params.set(key, value); } return params.toString(); }
async function load(): Promise<void> { loading.value = true; error.value = ''; try { const data = await apiRequest<{ items: GeoEntity[]; total?: number }>(`/v1/geodata/entities?${query()}`); entities.value = data.items || []; total.value = Number(data.total ?? entities.value.length); if (selected.value && !entities.value.some(item => item.id === selected.value?.id)) selected.value = null; } catch (e) { setError(e); } finally { loading.value = false; } }
async function loadCategories(): Promise<void> { try { const data = await apiRequest<{ items: EntityCategory[] }>('/v1/entity-types'); categories.value = data.items || []; } catch (e) { setError(e); } }
function selectEntity(entity: GeoEntity): void { selected.value = entity; editName.value = entity.name; editNote.value = ''; geometryNote.value = ''; geometryJson.value = entity.geometry ? JSON.stringify(entity.geometry, null, 2) : ''; editTypes.value = categoryCodes(entity); geometryType.value = entity.geometry?.type || 'Point'; selectedIds.value = [entity.id]; if (isManagement.value) window.setTimeout(() => document.getElementById('entity-editor')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); loadAudit(entity.id); }
async function loadAudit(id: string): Promise<void> { try { const data = await apiRequest<{ items: unknown[] }>(`/v1/geodata/entities/${encodeURIComponent(id)}/audit`); audit.value = data.items || []; } catch { audit.value = []; } }
function toggleStatus(status: string): void { filters.status = filters.status.includes(status) ? filters.status.filter(item => item !== status) : [...filters.status, status]; page.value = 1; load(); }
function toggleAll(): void { selectedIds.value = allSelected.value ? [] : entities.value.map(item => item.id); }
function toggleEntity(id: string): void { selectedIds.value = selectedIds.value.includes(id) ? selectedIds.value.filter(item => item !== id) : [...selectedIds.value, id]; }
function statusEvent(event: Event): string { return (event.target as HTMLSelectElement).value; }
async function saveStatus(status: string): Promise<void> { if (!selected.value) return; if (selected.value.status === 'APPROVED' && status !== 'RETIRED') { error.value = 'Approved entities can only be retired.'; return; } try { await apiRequest(`/v1/geodata/entities/${encodeURIComponent(selected.value.id)}/status`, { method: 'POST', body: JSON.stringify({ status, reviewerId: store.account?.id, note: editNote.value }) }); message.value = `Status changed to ${status}.`; await load(); const refreshed = entities.value.find(item => item.id === selected.value?.id); if (refreshed) selectEntity(refreshed); } catch (e) { setError(e); } }
async function bulkApprove(): Promise<void> { if (!selectedIds.value.length) return; try { const ids = [...selectedIds.value]; await Promise.all(ids.map(id => apiRequest(`/v1/geodata/entities/${encodeURIComponent(id)}/status`, { method: 'POST', body: JSON.stringify({ status: 'APPROVED', reviewerId: store.account?.id, note: 'Bulk approval from Geodata Review' }) }))); message.value = `${ids.length} entities queued for approval.`; selectedIds.value = []; await load(); } catch (e) { setError(e); } }
async function deleteEntity(id: string, confirmAction = true): Promise<void> { if (confirmAction && !window.confirm('Permanently delete this entity? If it has valid QSOs, all related QSOs will be deleted and awards may become invalid. This cannot be undone.')) return; try { await apiRequest(`/v1/activations/admin/entities/${encodeURIComponent(id)}/cascade-delete`, { method: 'POST', body: JSON.stringify({ deletedBy: store.account?.id }) }); await apiRequest(`/v1/geodata/entities/${encodeURIComponent(id)}/delete`, { method: 'POST', body: JSON.stringify({ deletedBy: store.account?.id }) }); message.value = 'Entity permanently deleted.'; selected.value = null; await load(); } catch (e) { setError(e); } }
async function bulkDelete(): Promise<void> { if (!selectedIds.value.length || !window.confirm(`Permanently delete ${selectedIds.value.length} entities? Valid QSOs will be deleted in cascade and awards may become invalid. This cannot be undone.`)) return; for (const id of selectedIds.value) await deleteEntity(id, false); selectedIds.value = []; }
async function saveName(): Promise<void> { if (!selected.value || !editName.value.trim()) return; try { await apiRequest(`/v1/geodata/entities/${encodeURIComponent(selected.value.id)}/name`, { method: 'POST', body: JSON.stringify({ name: editName.value.trim(), note: editNote.value, editorId: store.account?.id }) }); message.value = 'Entity name saved.'; await load(); const refreshed = entities.value.find(item => item.id === selected.value?.id); if (refreshed) selectEntity(refreshed); } catch (e) { setError(e); } }
async function saveCategories(): Promise<void> { if (!selected.value) return; try { await apiRequest(`/v1/geodata/entities/${encodeURIComponent(selected.value.id)}/entity-type`, { method: 'POST', body: JSON.stringify({ entityTypes: editTypes.value, entityTypeCodes: editTypes.value, editorId: store.account?.id }) }); message.value = 'Entity categories saved.'; await load(); } catch (e) { setError(e); } }
async function saveGeometry(): Promise<void> { if (!selected.value) return; try { const geometry = JSON.parse(geometryJson.value); geometry.type = geometryType.value; await apiRequest(`/v1/geodata/entities/${encodeURIComponent(selected.value.id)}/geometry-type`, { method: 'POST', body: JSON.stringify({ geometryType: geometryType.value, note: geometryNote.value, editorId: store.account?.id }) }); await apiRequest(`/v1/geodata/entities/${encodeURIComponent(selected.value.id)}/geometry`, { method: 'POST', body: JSON.stringify({ geometry, note: geometryNote.value, editorId: store.account?.id }) }); message.value = 'Geometry saved.'; await load(); } catch (e) { setError(e instanceof SyntaxError ? new Error('Geometry must be valid JSON.') : e); } }
function toggleNewType(code: string): void { newTypes.value = newTypes.value.includes(code) ? newTypes.value.filter(item => item !== code) : [...newTypes.value, code]; }
async function createCandidate(): Promise<void> { if (!newName.value.trim() || !newTypes.value.length) { error.value = 'Enter a name and select at least one category.'; return; } try { const geometry = JSON.parse(newGeometry.value); await apiRequest('/v1/geodata/proposals/draw', { method: 'POST', body: JSON.stringify({ programmeSlug: filters.programme || undefined, source: { name: 'Manual administration proposal', license: 'programme-supplied' }, feature: { properties: { name: newName.value.trim(), entityTypes: newTypes.value, entityTypeCodes: newTypes.value }, geometry } }) }); message.value = 'New candidate submitted.'; creating.value = false; newName.value = ''; newTypes.value = []; await load(); } catch (e) { setError(e instanceof SyntaxError ? new Error('Geometry must be valid JSON.') : e); } }
function setPage(next: number): void { page.value = next; load(); }
watch(() => [pageSize.value, filters.programme, filters.entityType, filters.continent, filters.country, filters.region, filters.province, filters.city], () => { page.value = 1; load(); });
onMounted(async () => { await Promise.all([loadCategories(), load()]); });
</script>

<template>
  <section class="page-heading"><div><p class="eyebrow">GEODATA</p><h1>{{ title }}</h1><p class="muted">{{ isManagement ? 'Edit catalogue data, geometry, categories and audit history.' : 'Review candidate entities and make durable status decisions.' }}</p></div><div class="heading-actions"><button class="secondary" @click="load">Refresh</button><button v-if="!isManagement" class="primary" @click="creating = !creating">New Candidate</button><button v-if="isManagement" class="primary" @click="selected = null">New entity</button></div></section>
  <div v-if="message" class="notice" role="status">{{ message }}</div><div v-if="error" class="error-card" role="alert">{{ error }}</div>
  <article class="panel filter-panel"><div class="top-controls"><label>Programme<select v-model="filters.programme"><option value="">All programmes, including unassigned</option><option v-for="programme in store.programmes" :key="programme.slug" :value="programme.slug">{{ programme.name }}</option></select></label><label>Quick status<select v-model="filters.status" multiple size="4"><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select></label></div><div class="geo-filter-grid"><label>Entity type<select v-model="filters.entityType"><option value="">All types</option><option v-for="category in categories" :key="category.code" :value="category.code">{{ category.label || category.code }}</option></select></label><label>Continent<input v-model="filters.continent"></label><label>Country<input v-model="filters.country"></label><label>Region / subdivision<input v-model="filters.region"></label><label>Province<input v-model="filters.province"></label><label>City / municipality<input v-model="filters.city"></label></div><div class="status-filters"><span>Status:</span><label v-for="status in statuses" :key="status"><input type="checkbox" :checked="filters.status.includes(status)" @change="toggleStatus(status)">{{ status }}</label></div></article>
  <article v-if="creating" class="panel"><div class="panel-heading"><div><p class="eyebrow">MANUAL PROPOSAL</p><h2>New Candidate</h2><p class="muted">Manual proposals enter the candidate queue and are not approved automatically.</p></div></div><form class="form-grid" @submit.prevent="createCandidate"><label>Name<input v-model="newName" required></label><label>Programme scope<select v-model="filters.programme"><option value="">Unassigned / platform-wide</option><option v-for="programme in store.programmes" :key="programme.slug" :value="programme.slug">{{ programme.name }}</option></select></label><fieldset class="wide"><legend>Entity categories</legend><div class="checkbox-grid"><label v-for="category in categories" :key="category.code"><input type="checkbox" :checked="newTypes.includes(category.code)" @change="toggleNewType(category.code)">{{ category.label || category.code }}</label></div></fieldset><label class="wide">GeoJSON geometry<textarea v-model="newGeometry" class="code-editor" required></textarea><small class="field-help">Use a Point, LineString, MultiLineString, Polygon or MultiPolygon geometry.</small></label><div class="form-actions wide"><button class="primary" type="submit">Submit candidate</button><button class="secondary" type="button" @click="creating = false">Cancel</button></div></form></article>
  <article class="panel"><div class="panel-heading"><div><h2>Entities</h2><small class="muted">{{ total }} matching entities · page {{ page }}</small></div><div class="toolbar"><label>Show <select v-model.number="pageSize"><option :value="10">10</option><option :value="25">25</option><option :value="50">50</option></select></label><label class="check-field"><input type="checkbox" :checked="allSelected" @change="toggleAll"><span>Select all</span></label><button v-if="!isManagement" class="primary" :disabled="!selectedIds.length" @click="bulkApprove">Change status to approved</button><button v-if="!isManagement && isGlobalAdmin" class="danger" :disabled="!selectedIds.length" @click="bulkDelete">Delete entities permanently</button></div></div><div class="geo-list"><div v-for="entity in entities" :key="entity.id" class="geo-row" :class="{ selected: selected?.id === entity.id }"><input type="checkbox" :checked="selectedIds.includes(entity.id)" @change="toggleEntity(entity.id)"><button class="entity-link" @click="selectEntity(entity)"><strong>{{ entity.name }}</strong><small>{{ categoryCodes(entity).join(', ') || 'Uncategorised' }} · {{ locationValue(entity, 'city') || 'Location unavailable' }}</small></button><span class="status-pill" :class="entity.status.toLowerCase()">{{ entity.status }}</span></div><p v-if="loading" class="muted empty">Loading entities…</p><p v-else-if="!entities.length" class="muted empty">No entities match these filters.</p></div><div class="pagination"><button class="secondary" :disabled="page <= 1" @click="setPage(page - 1)">Previous</button><span>{{ page }} / {{ Math.max(1, Math.ceil(total / pageSize)) }}</span><button class="secondary" :disabled="page * pageSize >= total" @click="setPage(page + 1)">Next</button></div></article>
  <article class="panel map-panel"><div class="panel-heading"><div><h2>Map</h2><small class="muted">Selecting an entity centres the map and opens its details.</small></div></div><LeafletMap :entities="entities" :selected-id="selected?.id" height="680px" @select="selectEntity"></LeafletMap></article>
  <article v-if="selected" id="entity-editor" class="panel editor-panel"><div class="panel-heading"><div><p class="eyebrow">{{ isManagement ? 'ENTITY MANAGEMENT' : 'REVIEW DECISION' }}</p><h2>{{ selected.name }}</h2><small class="muted">{{ selected.id }}</small></div><span class="status-pill" :class="selected.status.toLowerCase()">{{ selected.status }}</span></div><div class="editor-grid"><section v-if="isManagement" class="form-section"><h3>Name</h3><input v-model="editName"><textarea v-model="editNote" placeholder="Explain this name change"></textarea><button class="primary" @click="saveName">Save name</button></section><section class="form-section"><h3>Categories</h3><div class="checkbox-grid"><label v-for="category in categories" :key="category.code"><input v-model="editTypes" type="checkbox" :value="category.code">{{ category.label || category.code }}</label></div><button v-if="isManagement" class="secondary" @click="saveCategories">Save categories</button></section><section class="form-section"><h3>{{ isManagement ? 'Geometry editor' : 'Review decision' }}</h3><template v-if="isManagement"><label>Geometry type<select v-model="geometryType"><option>Point</option><option>LineString</option><option>MultiLineString</option><option>Polygon</option><option>MultiPolygon</option></select></label><textarea v-model="geometryJson" class="code-editor" placeholder="GeoJSON geometry"></textarea><textarea v-model="geometryNote" placeholder="Geometry change note"></textarea><button class="primary" @click="saveGeometry">Save geometry</button></template><template v-else><label>Status<select :value="selected.status" @change="saveStatus(statusEvent($event))"><option v-for="status in selectedStatusOptions" :key="status" :value="status">{{ status }}</option></select></label><textarea v-model="editNote" placeholder="Review note / decision evidence"></textarea><button class="primary" @click="saveStatus(selected.status)">Save review decision</button></template></section></div><section class="form-section"><h3>Location metadata</h3><div class="info-grid"><div><span>Continent</span><strong>{{ locationValue(selected, 'continent') || '—' }}</strong></div><div><span>Country</span><strong>{{ locationValue(selected, 'country') || '—' }}</strong></div><div><span>Region</span><strong>{{ locationValue(selected, 'region') || '—' }}</strong></div><div><span>Province</span><strong>{{ locationValue(selected, 'province') || '—' }}</strong></div><div><span>City</span><strong>{{ locationValue(selected, 'city') || '—' }}</strong></div></div></section><section v-if="isManagement" class="form-section"><h3>Audit history</h3><div class="audit-list"><div v-for="(item, index) in audit" :key="index">{{ typeof item === 'string' ? item : JSON.stringify(item) }}</div><p v-if="!audit.length" class="muted">No audit entries available.</p></div><button v-if="isGlobalAdmin" class="danger" @click="deleteEntity(selected.id)">Permanently delete entity</button></section></article>
</template>
