<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { apiRequest } from '../lib/api';
import { useAppStore } from '../stores/app';
interface Role { code: string; name: string; description?: string; scopes: string[]; system?: boolean; }
interface Account { id: string; displayName: string; email?: string; status: string; participationType?: string; callsigns?: Array<{ value: string }>; roles?: Array<{ role: string; programmeSlug?: string; jurisdiction?: string; entityType?: string }>; }
const store = useAppStore(); const accounts = ref<Account[]>([]); const roles = ref<Role[]>([]); const permissions = ref<any[]>([]); const securityEvents = ref<any[]>([]); const selectedAccount = ref<Account | null>(null); const selectedRole = ref<Role | null>(null); const search = ref(''); const message = ref('');
const accountForm = reactive({ displayName: '', email: '', status: 'ACTIVE', password: '', selectedRoles: [] as string[] }); const roleForm = reactive({ code: '', name: '', description: '', scopes: [] as string[] });
async function load(): Promise<void> { const [accountData, roleData] = await Promise.all([apiRequest<{ items: Account[] }>(`/v1/identity/admin/accounts?pageSize=100&q=${encodeURIComponent(search.value)}`), apiRequest<{ items: Role[]; permissions: any[] }>('/v1/identity/admin/roles')]); accounts.value = accountData.items || []; roles.value = roleData.items || []; permissions.value = roleData.permissions || []; try { securityEvents.value = (await apiRequest<{ items: any[] }>('/v1/identity/admin/security-events?pageSize=20')).items || []; } catch { securityEvents.value = []; } }
function editAccount(account: Account): void { selectedAccount.value = account; accountForm.displayName = account.displayName; accountForm.email = account.email || ''; accountForm.status = account.status; accountForm.password = ''; accountForm.selectedRoles = (account.roles || []).map(role => role.role); }
function editRole(role: Role | null): void { selectedRole.value = role; Object.assign(roleForm, { code: role?.code || '', name: role?.name || '', description: role?.description || '', scopes: [...(role?.scopes || [])] }); }
async function saveAccount(): Promise<void> { if (!selectedAccount.value) return; try { await apiRequest(`/v1/identity/admin/accounts/${encodeURIComponent(selectedAccount.value.id)}/update`, { method: 'POST', body: JSON.stringify({ displayName: accountForm.displayName, email: accountForm.email || null, status: accountForm.status, password: accountForm.password || undefined, roles: accountForm.selectedRoles.map(code => ({ code })) }), headers: { 'Idempotency-Key': crypto.randomUUID() } }); message.value = 'User updated.'; await load(); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to update user.'; } }
async function saveRole(): Promise<void> { try { await apiRequest(selectedRole.value ? `/v1/identity/admin/roles/${encodeURIComponent(selectedRole.value.code)}/update` : '/v1/identity/admin/roles', { method: 'POST', body: JSON.stringify({ code: roleForm.code.toUpperCase(), name: roleForm.name, description: roleForm.description, scopes: roleForm.scopes }), headers: { 'Idempotency-Key': crypto.randomUUID() } }); message.value = selectedRole.value ? 'Role updated.' : 'Role created.'; await load(); editRole(null); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to save role.'; } }
async function exportAccount(account: Account): Promise<void> { try { const data = await apiRequest<unknown>(`/v1/identity/accounts/${encodeURIComponent(account.id)}/export`); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `myota-account-${account.id}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to export account.'; } }
async function deactivateAccount(account: Account): Promise<void> { if (!window.confirm(`Deactivate and anonymize ${account.displayName}?`)) return; try { await apiRequest(`/v1/identity/accounts/${encodeURIComponent(account.id)}/deactivate`, { method: 'POST', body: JSON.stringify({ anonymize: true }) }); message.value = 'Account deactivated and anonymized.'; selectedAccount.value = null; await load(); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to deactivate account.'; } }
onMounted(load);
</script>

<template>
  <section class="page-heading"><div><p class="eyebrow">PEOPLE & ACCESS</p><h1>Identity administration</h1><p class="muted">Edit users, assign multiple roles, and define least-privilege administrative access.</p></div><button class="secondary" @click="load">Refresh</button></section><div v-if="message" class="notice" role="status">{{ message }}</div>
  <div class="identity-grid"><article class="panel"><div class="toolbar"><input v-model="search" placeholder="Search name or email" @keyup.enter="load"><button class="secondary" @click="load">Search</button></div><div class="table-list"><button v-for="account in accounts" :key="account.id" class="table-row" :class="{ selected: selectedAccount?.id === account.id }" @click="editAccount(account)"><span><strong>{{ account.displayName }}</strong><small>{{ account.email || 'No email' }} · {{ account.participationType || 'Operator' }}</small><small>{{ account.roles?.map(role => role.role).join(', ') || 'No admin roles' }}</small></span><span class="status-pill" :class="account.status === 'ACTIVE' ? 'approved' : 'muted-pill'">{{ account.status }}</span></button></div></article><article class="panel"><div class="panel-heading"><h2>User editor</h2></div><p v-if="!selectedAccount" class="muted empty">Choose a user to edit details and assigned roles.</p><form v-else class="form-grid" @submit.prevent="saveAccount"><label>Display name<input v-model="accountForm.displayName" required></label><label>Email<input v-model="accountForm.email" type="email"></label><label>Status<select v-model="accountForm.status"><option>ACTIVE</option><option>DEACTIVATED</option></select></label><label>Reset password<input v-model="accountForm.password" type="password" autocomplete="new-password" placeholder="Leave blank to keep current"><small class="field-help">Saving a password revokes existing sessions.</small></label><fieldset class="wide"><legend>Assigned roles</legend><div class="checkbox-grid"><label v-for="role in roles" :key="role.code" class="check-field"><input v-model="accountForm.selectedRoles" type="checkbox" :value="role.code"><span>{{ role.name }}<small class="field-help">{{ role.code }} · {{ role.scopes.join(', ') || 'No permissions' }}</small></span></label></div></fieldset><div class="form-actions wide"><button class="primary" type="submit">Save user</button><button class="secondary" type="button" @click="exportAccount(selectedAccount)">Export account</button><button v-if="selectedAccount.status === 'ACTIVE'" class="danger" type="button" @click="deactivateAccount(selectedAccount)">Deactivate and anonymize</button></div></form></article></div>
  <div class="identity-grid"><article class="panel"><div class="panel-heading"><h2>Roles and permissions</h2><button class="primary" @click="editRole(null)">New custom role</button></div><div class="table-list"><button v-for="role in roles" :key="role.code" class="table-row" :class="{ selected: selectedRole?.code === role.code }" @click="editRole(role)"><span><strong>{{ role.name }}</strong><small>{{ role.code }} · {{ role.scopes.join(', ') || 'No permissions' }}</small></span><span class="status-pill" :class="role.system ? 'system-role' : 'custom-role'">{{ role.system ? 'Built-in' : 'Custom' }}</span></button></div></article><article class="panel"><div class="panel-heading"><h2>{{ selectedRole ? selectedRole.name : 'Create a custom role' }}</h2></div><form class="form-grid" @submit.prevent="saveRole"><label>Role code<input v-model="roleForm.code" :readonly="Boolean(selectedRole)" required></label><label>Display name<input v-model="roleForm.name" required></label><label class="wide">Description<textarea v-model="roleForm.description"></textarea></label><fieldset class="wide"><legend>Administrative permissions</legend><div class="checkbox-grid"><label v-for="permission in permissions" :key="permission.code" class="check-field"><input v-model="roleForm.scopes" type="checkbox" :value="permission.code" :disabled="Boolean(selectedRole?.system)"><span>{{ permission.code }}<small class="field-help">{{ permission.label }}</small></span></label></div></fieldset><div class="form-actions wide"><button class="primary" type="submit" :disabled="Boolean(selectedRole?.system)">Save role</button></div></form></article></div>
  <article class="panel"><div class="panel-heading"><div><p class="eyebrow">AUDIT CONTEXT</p><h2>Recent security events</h2></div><button class="secondary" @click="load">Refresh</button></div><div class="table-list"><div v-for="event in securityEvents" :key="event.id || event.occurredAt" class="table-row"><span><strong>{{ event.eventType }}</strong><small>{{ event.occurredAt }} · {{ event.payload?.accountId || 'system' }}</small></span></div><p v-if="!securityEvents.length" class="muted empty">No recent security events.</p></div></article>
</template>
