<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { apiRequest } from '../lib/api';
import type { EntityCategory } from '../types';
const geometryTypes = ['POINT', 'LINESTRING', 'MULTILINESTRING', 'POLYGON', 'MULTIPOLYGON'];
const labels: Record<string, string> = { POINT: 'Point', LINESTRING: 'LineString', MULTILINESTRING: 'MultiLineString', POLYGON: 'Polygon', MULTIPOLYGON: 'MultiPolygon' };
const items = ref<EntityCategory[]>([]); const selected = ref<EntityCategory | null>(null); const message = ref('');
const form = reactive({ code: '', label: '', description: '', active: true, geometryTypes: ['MULTIPOLYGON'] });
function edit(item: EntityCategory | null): void { selected.value = item; Object.assign(form, { code: item?.code || '', label: item?.label || '', description: item?.description || '', active: item?.active !== false, geometryTypes: [...(item?.geometryTypes || (item?.geometry ? [item.geometry] : ['MULTIPOLYGON']))] }); }
async function load(selectedCode?: string | Event): Promise<void> { const code = typeof selectedCode === 'string' ? selectedCode : undefined; const data = await apiRequest<{ items: EntityCategory[] }>('/v1/entity-types'); items.value = data.items || []; if (code) edit(items.value.find(item => item.code === code) || null); }
async function save(): Promise<void> { if (!/^[A-Z][A-Z0-9_]{1,63}$/.test(form.code)) { message.value = 'Category code must use uppercase letters, numbers, and underscores.'; return; } if (!form.geometryTypes.length) { message.value = 'Select at least one geometry type.'; return; } try { await apiRequest('/v1/entity-types', { method: 'POST', body: JSON.stringify({ code: form.code, originalCode: selected.value?.code || form.code, label: form.label, description: form.description, active: form.active, geometryTypes: form.geometryTypes }), headers: { 'Idempotency-Key': crypto.randomUUID() } }); message.value = 'Category saved.'; await load(form.code); } catch (error) { message.value = error instanceof Error ? error.message : 'Unable to save category.'; } }
onMounted(() => load());
</script>

<style scoped>
.master-data-form > label {
  align-content: start;
}
</style>

<template>
  <section class="page-heading"><div><p class="eyebrow">PLATFORM CATALOGUE</p><h1>Master data</h1><p class="muted">Manage shared entity categories used by imports, review, activity and awards.</p></div><button class="secondary" @click="load">Refresh</button></section>
  <div class="toolbar"><span class="toolbar-context">Shared catalogue · assignments are managed from Programme Management</span><button class="primary" @click="edit(null)">New category</button></div><div v-if="message" class="notice" role="status">{{ message }}</div>
  <div class="split-layout"><article class="panel"><div class="panel-heading"><h2>Entity categories</h2></div><div class="table-list"><button v-for="item in items" :key="item.code" class="table-row" :class="{ selected: selected?.code === item.code }" @click="edit(item)"><span><strong>{{ item.label || item.code }}</strong><small><code>{{ item.code }}</code> · {{ (item.geometryTypes || []).map(type => labels[type] || type).join(', ') }}</small><small>{{ item.active === false ? 'Inactive' : 'Active' }} · {{ item.assignedProgrammes?.length || 0 }} programme(s)</small></span><span class="status-pill" :class="item.active === false ? 'muted-pill' : 'approved'">{{ item.active === false ? 'Inactive' : 'Active' }}</span></button><p v-if="!items.length" class="muted empty">No shared categories configured.</p></div></article><article class="panel"><div class="panel-heading"><h2>{{ selected ? `Edit ${selected.label || selected.code}` : 'New category' }}</h2></div><form class="form-grid master-data-form" @submit.prevent="save"><label>Category code<input v-model="form.code" :readonly="Boolean(selected)" required><small class="field-help">Stable identifier. Codes cannot be renamed after creation.</small></label><label>Display name<input v-model="form.label" required></label><fieldset class="wide"><legend>Allowed geometry types</legend><div class="checkbox-grid"><label v-for="type in geometryTypes" :key="type" class="check-field"><input v-model="form.geometryTypes" type="checkbox" :value="type"><span>{{ labels[type] }}</span></label></div></fieldset><label>Availability<select v-model="form.active"><option :value="true">Active — available for new entities</option><option :value="false">Inactive — retain historical entities</option></select></label><label class="wide">Description<textarea v-model="form.description"></textarea></label><div class="form-actions wide"><button class="primary" type="submit">Save category</button><button class="secondary" type="button" @click="edit(null)">Clear form</button></div></form></article></div>
  <article class="panel"><div class="panel-heading"><h2>Shared category rules</h2></div><div class="info-grid"><p><strong>Stable code</strong><br><span class="muted">Stored with entities and referenced by programme rules and awards.</span></p><p><strong>Multiple geometries</strong><br><span class="muted">A category may permit Point, LineString, MultiLineString, Polygon and MultiPolygon.</span></p><p><strong>Inactive lifecycle</strong><br><span class="muted">Existing records retain historical categories while new assignments are prevented.</span></p></div></article>
</template>
