<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue';
import { apiRequest } from '../lib/api';
import { myotaClient } from '../lib/myotaClient';
import { useAppStore } from '../stores/app';
import { utcInput, utcInputValue } from '../lib/utc';

interface Policy { id?: string; type: string; name: string; schema?: unknown; effectiveFrom?: string; status?: string; }
const store = useAppStore();
const policies = ref<Policy[]>([]); const selected = ref<Policy | null>(null); const message = ref('');
const form = reactive({ type: 'RULES', name: '', effectiveFrom: '', schema: '{\n  "rules": {\n    "minimumQsos": { "activation": 0, "hunter": 0 }\n  }\n}' });
const programme = ref(store.currentProgramme || store.programmes[0]?.slug || '');
function edit(policy: Policy | null): void { selected.value = policy; Object.assign(form, { type: policy?.type || 'RULES', name: policy?.name || '', effectiveFrom: utcInput(policy?.effectiveFrom), schema: JSON.stringify(policy?.schema || { rules: { minimumQsos: { activation: 0, hunter: 0 } } }, null, 2) }); }
async function load(selectedId?: string | Event): Promise<void> { if (!programme.value) return; const id = typeof selectedId === 'string' ? selectedId : undefined; const data = await apiRequest<{ items: Policy[] }>(`/v1/programmes/${encodeURIComponent(programme.value)}/policy-drafts?pageSize=100`); policies.value = data.items || []; if (id) edit(policies.value.find(item => item.id === id) || null); }
async function save(): Promise<void> { try { const saved = await apiRequest<Policy>(`/v1/programmes/${encodeURIComponent(programme.value)}/policy-drafts`, { method: 'POST', body: JSON.stringify({ draftId: selected.value?.id, type: form.type, name: form.name.trim(), schema: JSON.parse(form.schema), effectiveFrom: utcInputValue(form.effectiveFrom, selected.value?.effectiveFrom) }) }); message.value = 'Policy draft saved.'; await load(saved.id); } catch (error) { message.value = error instanceof Error ? error.message : 'Invalid policy draft.'; } }
async function action(action: string, decision?: string): Promise<void> { if (!selected.value?.id) return; try { if (action === 'publish' && !form.effectiveFrom) throw new Error('Choose an effective date before publishing.'); const body = action === 'review' ? { status: decision, reviewerId: store.account?.id, note: 'Reviewed in programme administration' } : action === 'publish' ? { status: 'PUBLISHED', effectiveFrom: utcInputValue(form.effectiveFrom, selected.value?.effectiveFrom), publisherId: store.account?.id } : { status: 'UNDER_REVIEW', submitterId: store.account?.id }; await myotaClient.patchProgrammePolicyDraft(programme.value, selected.value.id, body); message.value = `Policy ${action === 'publish' ? 'published' : `${action}ed`}.`; await load(selected.value.id); } catch (error) { message.value = error instanceof Error ? error.message : 'Policy action failed.'; } }
watch(programme, () => { store.currentProgramme = programme.value; load(); }); onMounted(() => load());
</script>

<template>
  <section class="page-heading"><div><p class="eyebrow">PROGRAMME POLICY</p><h1>Rules & awards</h1><p class="muted">Draft, review and explicitly publish programme-owned rules and awards.</p></div><button class="primary" @click="edit(null)">New draft</button></section>
  <div class="toolbar"><label class="toolbar-field">Programme<select v-model="programme"><option v-for="item in store.programmes" :key="item.slug" :value="item.slug">{{ item.name }}</option></select></label><button class="secondary" @click="load">Refresh</button></div>
  <div v-if="message" class="notice" role="status">{{ message }}</div>
  <div class="split-layout"><article class="panel"><div class="panel-heading"><h2>Policy drafts</h2></div><div class="table-list"><button v-for="item in policies" :key="item.id" class="table-row" :class="{ selected: selected?.id === item.id }" @click="edit(item)"><span><strong>{{ item.name }}</strong><small>{{ item.type }} · {{ item.effectiveFrom || 'No effective date' }}</small></span><span class="status-pill" :class="(item.status || '').toLowerCase()">{{ item.status }}</span></button><p v-if="!policies.length" class="muted empty">No drafts yet.</p></div></article><article class="panel"><div class="panel-heading"><h2>{{ selected ? selected.name : 'New rule or award draft' }}</h2><span v-if="selected" class="status-pill" :class="(selected.status || '').toLowerCase()">{{ selected.status }}</span></div><form class="form-grid" @submit.prevent="save"><label>Policy type<select v-model="form.type"><option value="RULES">Rules</option><option value="AWARD">Award</option></select></label><label>Name<input v-model="form.name" required></label><label>Effective from (UTC)<input v-model="form.effectiveFrom" type="datetime-local"></label><label class="wide">Programme-owned schema (JSON)<textarea v-model="form.schema" class="code-editor" required></textarea><small class="field-help">The programme owns the schema and its meaning. Published versions are immutable.</small></label><div class="form-actions wide"><button class="primary" type="submit">Save draft</button><button v-if="selected && ['DRAFT','CHANGES_REQUESTED'].includes(selected.status || '')" class="secondary" type="button" @click="action('submit')">Submit for review</button><button v-if="selected?.status === 'UNDER_REVIEW'" class="approve" type="button" @click="action('review', 'APPROVED')">Approve</button><button v-if="selected?.status === 'UNDER_REVIEW'" class="reject" type="button" @click="action('review', 'CHANGES_REQUESTED')">Request changes</button><button v-if="selected?.status === 'APPROVED'" class="primary" type="button" @click="action('publish')">Publish</button></div></form></article></div>
</template>
